<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net9.0-windows;net10.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <OutputType>Exe</OutputType>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <XamlDebuggingInformation>true</XamlDebuggingInformation>
  </PropertyGroup>
</Project>
