using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WpfStudio.Workspace.Xaml;

internal sealed record XamlGeneratedNameSource(string Path, string Text);
internal enum XamlGeneratedNameBridgeState { Verified, NoGeneratedField, NotGeneratedField, Unavailable }
internal sealed record XamlGeneratedNameBridgeResult(XamlGeneratedNameBridgeState State, IFieldSymbol? Field = null,
    string? Path = null, int Start = 0, int Length = 0, string? Status = null);

/// <summary>Checks current WPF compiler output against authored XAML without executing project code.</summary>
internal static class XamlGeneratedNameBridge
{
    internal const int MaximumSourceBytes = 4_000_000;
    private const int MaximumGeneratedCharacters = 2_000_000;
    private static readonly Guid Sha1 = new("ff1816ec-aa5e-4d10-87f7-6f4963833460");
    private static readonly Guid Sha256 = new("8829d00f-11b8-4213-878b-770e8597ac16");
    private sealed record Authored(XamlNameScopeIndex Index, XamlNameScopeIndex.Declaration Declaration,
        XamlSyntax.Element Root, INamedTypeSymbol? RootType);

    internal static async Task<XamlGeneratedNameBridgeResult> FromFieldAsync(Project project, Compilation compilation,
        IFieldSymbol field, IReadOnlyList<XamlGeneratedNameSource> sources, CancellationToken token = default,
        byte[]? baselineSourceBytes = null)
    {
        token.ThrowIfCancellationRequested();
        var references = field.DeclaringSyntaxReferences;
        if (!references.Any(reference => GeneratedPath(reference.SyntaxTree.FilePath)))
            return new(XamlGeneratedNameBridgeState.NotGeneratedField, Status: "This field is not declared in a WPF generated document.");
        if (references.Length != 1 || field.IsStatic || field.IsConst || field.IsImplicitlyDeclared)
            return Unavailable("The generated field is not a unique instance field.");
        if (sources.Count > 512) return Unavailable("Generated-name verification exceeds the 512-source limit.");
        var tree = references[0].SyntaxTree;
        var document = project.Solution.GetDocument(tree);
        if (document is null || document.Project.Id != project.Id || !compilation.ContainsSyntaxTree(tree)
            || !ReferenceEquals(await document.GetSyntaxTreeAsync(token).ConfigureAwait(false), tree))
            return Unavailable("The generated declaration is not a document in the current project compilation.");
        if (await references[0].GetSyntaxAsync(token).ConfigureAwait(false) is not VariableDeclaratorSyntax variable
            || variable.Parent?.Parent is not FieldDeclarationSyntax declaration || declaration.Declaration.Variables.Count != 1
            || !SymbolEqualityComparer.Default.Equals(compilation.GetSemanticModel(tree).GetDeclaredSymbol(variable, token), field))
            return Unavailable("The current compiler field declaration could not be verified.");
        var generated = await tree.GetTextAsync(token).ConfigureAwait(false);
        if (generated.Length > MaximumGeneratedCharacters
            || !generated.ToString(new TextSpan(0, Math.Min(generated.Length, 4096))).Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || !HasWpfProducer(field.ContainingType, tree, compilation, token))
            return Unavailable("The document does not carry supported WPF compiler provenance.");

        // WPF puts SuppressMessage before the field. Mapping the identifier alone
        // therefore advances one line beyond the authored name attribute.
        var mapped = tree.GetMappedLineSpan(new TextSpan(declaration.SpanStart, 0), token);
        if (!mapped.IsValid || !mapped.HasMappedPath || string.IsNullOrWhiteSpace(mapped.Path))
            return Unavailable("The generated field has no authored XAML line mapping.");
        string? mappedPath = ResolvePath(mapped.Path, tree.FilePath);
        if (mappedPath is null) return Unavailable("The generated field's mapped XAML path is unsupported.");
        var inputs = sources.Where(source => SamePath(source.Path, mappedPath)).Take(2).ToArray();
        if (inputs.Length != 1) return Unavailable("The generated field does not map to one evaluated XAML source in this project.");
        var source = inputs[0];
        var authored = FindAuthored(source, compilation, field.Name, null, token, out string? status);
        if (authored is null) return Unavailable(status!);
        if (authored.Declaration.Scope.Kind != "page" || !ReferenceEquals(authored.Declaration.Scope.Owner, authored.Root)
            || authored.RootType is null || !SymbolEqualityComparer.Default.Equals(authored.RootType, field.ContainingType)
            || !SymbolEqualityComparer.Default.Equals(authored.Declaration.Type, field.Type))
            return Unavailable("The generated field does not match the authored page class, name scope, and element type.");
        int line = SourceText.From(source.Text).Lines.GetLineFromPosition(authored.Declaration.Attribute.NameStart).LineNumber;
        if (mapped.StartLinePosition.Line != line)
            return Unavailable("The generated field's line mapping no longer matches the authored name attribute.");

        var syntax = await tree.GetRootAsync(token).ConfigureAwait(false);
        var checksums = new List<PragmaChecksumDirectiveTriviaSyntax>();
        int directives = 0;
        foreach (var trivia in syntax.DescendantTrivia(descendIntoTrivia: true))
        {
            token.ThrowIfCancellationRequested();
            if (!trivia.HasStructure || trivia.GetStructure() is not DirectiveTriviaSyntax directive) continue;
            if (++directives > 16_384) return Unavailable("Generated-name verification exceeded its directive budget.");
            if (directive is PragmaChecksumDirectiveTriviaSyntax checksum && checksum.IsActive
                && SamePath(ResolvePath(checksum.File.ValueText, tree.FilePath), mappedPath)) checksums.Add(checksum);
        }
        if (checksums.Count != 1 || !Guid.TryParse(checksums[0].Guid.ValueText, out var algorithm)
            || algorithm != Sha1 && algorithm != Sha256)
            return Unavailable("The generated document has no unique supported checksum for this XAML source.");
        byte[] expected;
        try { expected = Convert.FromHexString(checksums[0].Bytes.ValueText); }
        catch (FormatException) { return Unavailable("The compiler's XAML checksum is malformed."); }
        if (expected.Length != (algorithm == Sha1 ? 20 : 32)) return Unavailable("The compiler's XAML checksum has an invalid length.");
        try
        {
            // Replay supplies the original compiler input explicitly. It must
            // still match both the pragma checksum and the exact decoded source;
            // this never re-labels current edited XAML as compiled input.
            byte[] bytes = baselineSourceBytes ?? await ReadSourceBytesAsync(source.Path, token).ConfigureAwait(false);
            if (bytes.Length > MaximumSourceBytes) return Unavailable("The XAML byte budget was exceeded.");
            token.ThrowIfCancellationRequested();
            byte[] actual = algorithm == Sha1 ? SHA1.HashData(bytes) : SHA256.HashData(bytes);
            if (!CryptographicOperations.FixedTimeEquals(actual, expected))
                return Unavailable("The current XAML bytes differ from the compiler checksum; rebuild before using the generated field.");
            if (!string.Equals(DecodeSourceBytes(bytes), source.Text, StringComparison.Ordinal))
                return Unavailable("The current XAML buffer differs from the source used to generate this field; save and rebuild first.");
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or DecoderFallbackException or NotSupportedException or RegexMatchTimeoutException)
        { return Unavailable("The exact XAML source bytes could not be verified: " + exception.Message); }
        token.ThrowIfCancellationRequested();
        return new(XamlGeneratedNameBridgeState.Verified, field, source.Path, authored.Declaration.Start, authored.Declaration.Length);
    }

    internal static async Task<XamlGeneratedNameBridgeResult> FromDeclarationAsync(Project project, Compilation compilation,
        XamlGeneratedNameSource source, int declarationStart, CancellationToken token = default,
        byte[]? baselineSourceBytes = null)
    {
        token.ThrowIfCancellationRequested();
        var authored = FindAuthored(source, compilation, null, declarationStart, token, out string? status);
        if (authored is null) return Unavailable(status!);
        if (authored.Declaration.Scope.Kind == "template")
            return new(XamlGeneratedNameBridgeState.NoGeneratedField, Path: source.Path, Start: authored.Declaration.Start,
                Length: authored.Declaration.Length, Status: "Template-local names do not imply a page field.");
        if (authored.Declaration.Scope.Kind != "page" || !ReferenceEquals(authored.Declaration.Scope.Owner, authored.Root))
            return Unavailable("The declaration's generated-field scope cannot be established.");
        if (authored.Root.Attribute(XamlSyntax.Language, "Class") is null)
            return new(XamlGeneratedNameBridgeState.NoGeneratedField, Path: source.Path, Start: authored.Declaration.Start,
                Length: authored.Declaration.Length, Status: "This XAML document has no x:Class page field.");
        if (authored.RootType is null) return Unavailable("The current x:Class type is unavailable.");
        var members = authored.RootType.GetMembers(authored.Declaration.Name);
        if (members is not [IFieldSymbol field]) return Unavailable("The page has no unique compiler field for this name; save and rebuild first.");
        var result = await FromFieldAsync(project, compilation, field, [source], token, baselineSourceBytes).ConfigureAwait(false);
        return result.State == XamlGeneratedNameBridgeState.NotGeneratedField
            ? Unavailable("The matching page member is authored C# rather than a verified WPF field.") : result;
    }

    private static Authored? FindAuthored(XamlGeneratedNameSource source, Compilation compilation, string? name,
        int? start, CancellationToken token, out string? status)
    {
        status = "The XAML name declaration is missing, ambiguous, or in an unsupported scope.";
        if (source.Text.Length > XamlNameScopeIndex.MaximumCharacters) { status = "The XAML source exceeds the name-analysis text budget."; return null; }
        try
        {
            using var reader = XmlReader.Create(new StringReader(source.Text), new XmlReaderSettings
            { DtdProcessing = DtdProcessing.Prohibit, XmlResolver = null, MaxCharactersInDocument = XamlNameScopeIndex.MaximumCharacters });
            int count = 0;
            while (reader.Read())
            {
                token.ThrowIfCancellationRequested();
                if (reader.Depth > 256 || reader.NodeType == XmlNodeType.Element && ++count > XamlNameScopeIndex.MaximumElements)
                { status = "The XAML source exceeds the name-analysis structural budget."; return null; }
            }
        }
        catch (XmlException) { status = "Generated-name verification requires well-formed XAML."; return null; }
        var elements = XamlSyntax.Read(source.Text, token);
        var roots = elements.Where(element => element.Parent is null).Take(2).ToArray();
        if (roots.Length != 1) return null;
        var index = new XamlNameScopeIndex(elements, compilation, token);
        if (!index.IsComplete) { status = index.Status; return null; }
        var matches = index.Declarations.Where(item => (name is null || item.Name == name) && (start is null || item.Start == start)
            && (start is not null || item.Scope.Kind == "page" && ReferenceEquals(item.Scope.Owner, roots[0]))
            && index.GetDeclaration(item.Element) == item.Attribute).Take(2).ToArray();
        if (matches.Length != 1) return null;
        var root = roots[0];
        INamedTypeSymbol? rootType = null;
        if (root.Attribute(XamlSyntax.Language, "Class") is { } classAttribute)
        {
            var types = new SchemaTypeResolver(compilation, token);
            var lexical = types.Resolve(root, root.Name);
            var actual = types.ResolveMetadataName(classAttribute.Value.Text.Trim(), null);
            if (lexical is not null && actual is not null && SchemaMembers.IsComplete(actual) && SchemaMembers.DerivesFrom(actual, lexical)) rootType = actual;
        }
        return new(index, matches[0], root, rootType);
    }

    private static bool HasWpfProducer(INamedTypeSymbol owner, SyntaxTree tree, Compilation compilation, CancellationToken token)
    {
        INamedTypeSymbol? Canonical(string name, params string[] assemblies)
        {
            var matches = compilation.SourceModule.ReferencedAssemblySymbols.Where(assembly => assemblies.Contains(assembly.Identity.Name, StringComparer.Ordinal))
                .Select(assembly => assembly.GetTypeByMetadataName(name) ?? assembly.ResolveForwardedType(name))
                .OfType<INamedTypeSymbol>().Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default).Take(2).ToArray();
            return matches.Length == 1 ? matches[0] : null;
        }
        var connector = Canonical("System.Windows.Markup.IComponentConnector", "PresentationFramework", "WindowsBase", "System.Xaml");
        var generatedCode = Canonical("System.CodeDom.Compiler.GeneratedCodeAttribute", "System.Runtime", "System.Private.CoreLib", "System.CodeDom", "System", "mscorlib");
        if (connector is null || generatedCode is null || !owner.AllInterfaces.Any(item => SymbolEqualityComparer.Default.Equals(item, connector))) return false;
        token.ThrowIfCancellationRequested();
        return owner.GetMembers("InitializeComponent").OfType<IMethodSymbol>().Any(method => !method.IsStatic && method.ReturnsVoid
            && method.Parameters.Length == 0 && method.DeclaringSyntaxReferences.Any(reference => ReferenceEquals(reference.SyntaxTree, tree))
            && method.GetAttributes().Any(attribute => SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, generatedCode)
                && attribute.ConstructorArguments is [{ Value: "PresentationBuildTasks" }, { Value: string }]));
    }

    internal static async Task<byte[]> ReadSourceBytesAsync(string path, CancellationToken token)
    {
        await using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 16_384, FileOptions.Asynchronous | FileOptions.SequentialScan);
        if (stream.Length > MaximumSourceBytes) throw new IOException("The XAML byte budget was exceeded.");
        using var output = new MemoryStream((int)stream.Length);
        byte[] buffer = new byte[16_384];
        while (true)
        {
            int read = await stream.ReadAsync(buffer, token).ConfigureAwait(false);
            if (read == 0) break;
            if (output.Length + read > MaximumSourceBytes) throw new IOException("The XAML byte budget was exceeded.");
            output.Write(buffer, 0, read);
        }
        return output.ToArray();
    }

    internal static string DecodeSourceBytes(byte[] bytes)
    {
        int skip = 0;
        Encoding encoding = new UTF8Encoding(false, true);
        if (bytes.AsSpan().StartsWith(new byte[] { 0, 0, 0xFE, 0xFF })) { encoding = new UTF32Encoding(true, false, true); skip = 4; }
        else if (bytes.AsSpan().StartsWith(new byte[] { 0xFF, 0xFE, 0, 0 })) { encoding = new UTF32Encoding(false, false, true); skip = 4; }
        else if (bytes.AsSpan().StartsWith(new byte[] { 0xEF, 0xBB, 0xBF })) skip = 3;
        else if (bytes.AsSpan().StartsWith(new byte[] { 0xFF, 0xFE })) { encoding = new UnicodeEncoding(false, false, true); skip = 2; }
        else if (bytes.AsSpan().StartsWith(new byte[] { 0xFE, 0xFF })) { encoding = new UnicodeEncoding(true, false, true); skip = 2; }
        else if (bytes.AsSpan().StartsWith(new byte[] { 0, 0, 0, 0x3C })) encoding = new UTF32Encoding(true, false, true);
        else if (bytes.AsSpan().StartsWith(new byte[] { 0x3C, 0, 0, 0 })) encoding = new UTF32Encoding(false, false, true);
        else if (bytes.AsSpan().StartsWith(new byte[] { 0, 0x3C, 0, 0x3F })) encoding = new UnicodeEncoding(true, false, true);
        else if (bytes.AsSpan().StartsWith(new byte[] { 0x3C, 0, 0x3F, 0 })) encoding = new UnicodeEncoding(false, false, true);
        string text = encoding.GetString(bytes, skip, bytes.Length - skip);
        // Do not silently reinterpret a declaration for a legacy/code-page encoding.
        var declaration = Regex.Match(text.Length > 1024 ? text[..1024] : text,
            "\\A<\\?xml\\s[^?]*?encoding\\s*=\\s*(['\"])(?<name>[^'\"]+)\\1", RegexOptions.CultureInvariant, TimeSpan.FromMilliseconds(100));
        if (declaration.Success)
        {
            string name = declaration.Groups["name"].Value.ToLowerInvariant();
            bool compatible = encoding.CodePage switch
            {
                65001 => name is "utf-8" or "utf8",
                1200 => name is "utf-16" or "utf-16le" or "unicode",
                1201 => name is "utf-16" or "utf-16be",
                12000 => name is "utf-32" or "utf-32le",
                12001 => name is "utf-32" or "utf-32be",
                _ => false
            };
            if (!compatible) throw new NotSupportedException("The XML encoding declaration is unsupported or disagrees with its bytes.");
        }
        return text;
    }

    private static bool GeneratedPath(string path) => path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) || path.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase);
    private static string? ResolvePath(string value, string generatedPath)
    {
        try { return string.IsNullOrWhiteSpace(value) ? null : Path.GetFullPath(value, Path.GetDirectoryName(Path.GetFullPath(generatedPath))!); }
        catch (Exception exception) when (exception is ArgumentException or NotSupportedException or PathTooLongException) { return null; }
    }
    private static bool SamePath(string? left, string? right)
    {
        if (left is null || right is null) return false;
        try { return string.Equals(Path.GetFullPath(left), Path.GetFullPath(right), StringComparison.OrdinalIgnoreCase); }
        catch (Exception exception) when (exception is ArgumentException or NotSupportedException or PathTooLongException) { return false; }
    }
    private static XamlGeneratedNameBridgeResult Unavailable(string status) => new(XamlGeneratedNameBridgeState.Unavailable, Status: status);
}
