using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using WpfStudio.Contracts;

namespace WpfStudio.Workspace.Xaml;

internal sealed record XamlEventHandlerProposal(string Path, string OriginalText, TextEdit Edit);

/// <summary>Proposes source text only; no project code is loaded, executed, saved, or reformatted.</summary>
internal static class XamlEventHandlerGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
        SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers | SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
        SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public static async Task<XamlEventHandlerProposal?> CreateAsync(Project project, Compilation compilation,
        XamlEventTarget target, CancellationToken token = default, string? xamlPath = null)
    {
        token.ThrowIfCancellationRequested();
        if (project.Language != LanguageNames.CSharp || compilation is not CSharpCompilation ||
            target.RootClass.TypeKind != TypeKind.Class || target.RootClass.IsStatic || target.RootClass.IsGenericType ||
            target.RootClass.ContainingType is not null || target.RootClass.IsImplicitlyDeclared ||
            !SymbolEqualityComparer.Default.Equals(target.RootClass.ContainingAssembly, compilation.Assembly) ||
            !SymbolEqualityComparer.Default.Equals(target.InvokeMethod, target.DelegateType.DelegateInvokeMethod) ||
            EscapeIdentifier(target.HandlerName) is not { } handlerName || target.InvokeMethod.ReturnsByRef ||
            target.InvokeMethod.ReturnsByRefReadonly || target.InvokeMethod.Parameters.Length > 32) return null;
        for (var type = target.RootClass; type is not null; type = type.BaseType)
            if (type.GetMembers(target.HandlerName).Length != 0) return null;
        if (target.RootClass.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() is
            "System.CodeDom.Compiler.GeneratedCodeAttribute" or "System.Runtime.CompilerServices.CompilerGeneratedAttribute")) return null;
        if (!SupportedType(target.DelegateType, compilation, target.RootClass) ||
            !SupportedType(target.InvokeMethod.ReturnType, compilation, target.RootClass)) return null;

        var declarations = new List<(Document Document, ClassDeclarationSyntax Declaration, SourceText Text)>();
        foreach (var reference in target.RootClass.DeclaringSyntaxReferences)
        {
            token.ThrowIfCancellationRequested();
            if (project.GetDocument(reference.SyntaxTree) is not { FilePath: { } path } document || GeneratedPath(path)) continue;
            if (await reference.GetSyntaxAsync(token).ConfigureAwait(false) is not ClassDeclarationSyntax declaration) return null;
            var text = await document.GetTextAsync(token).ConfigureAwait(false);
            if (text.Length > 2_000_000 || text.ToString(new TextSpan(0, Math.Min(text.Length, 4096))).Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) continue;
            declarations.Add((document, declaration, text));
        }
        // A conventional code-behind file disambiguates ordinary logic partials.
        // Otherwise require one authored declaration instead of choosing a fragment.
        var conventional = xamlPath is null ? [] : declarations.Where(item => string.Equals(
            Path.GetFullPath(item.Document.FilePath!), Path.GetFullPath(xamlPath + ".cs"), StringComparison.OrdinalIgnoreCase)).ToArray();
        if (conventional.Length > 1 || conventional.Length == 0 && declarations.Count != 1) return null;
        var (source, classDeclaration, before) = conventional.Length == 1 ? conventional[0] : declarations[0];
        string sourcePath = Path.GetFullPath(source.FilePath!);
        if (!File.Exists(sourcePath) || project.Solution.GetDocumentIdsWithFilePath(sourcePath).Length != 1 ||
            !classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword) || classDeclaration.ContainsDiagnostics ||
            classDeclaration.OpenBraceToken.IsMissing || classDeclaration.CloseBraceToken.IsMissing) return null;
        var root = await source.GetSyntaxRootAsync(token).ConfigureAwait(false);
        if (root is null) return null;
        try { if ((File.GetAttributes(sourcePath) & FileAttributes.ReadOnly) != 0) return null; }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException) { return null; }

        var parameters = new List<string>();
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var parameter in target.InvokeMethod.Parameters)
        {
            if (!SupportedType(parameter.Type, compilation, target.RootClass)) return null;
            string modifier = parameter.RefKind switch
            {
                RefKind.None => "", RefKind.Ref => "ref ", RefKind.Out => "out ", RefKind.In => "in ",
                _ => "unsupported"
            };
            if (modifier == "unsupported") return null;
            // Out parameters are scoped by default. Other scoped by-reference
            // contracts need the explicit modifier, checked in the project's language version below.
            if (parameter.ScopedKind != ScopedKind.None && parameter.RefKind != RefKind.Out) modifier = "scoped " + modifier;
            string name = parameter.Name;
            if (EscapeIdentifier(name) is null || !names.Add(name))
            {
                name = "arg" + (parameters.Count + 1);
                while (!names.Add(name)) name += "_";
            }
            parameters.Add(modifier + parameter.Type.ToDisplayString(TypeFormat) + " " + EscapeIdentifier(name));
        }
        string body = target.InvokeMethod.ReturnsVoid && target.InvokeMethod.Parameters.All(parameter => parameter.RefKind != RefKind.Out)
            ? "{ }" : "{ throw new global::System.NotImplementedException(); }";
        string signature = $"private {target.InvokeMethod.ReturnType.ToDisplayString(TypeFormat)} {handlerName}({string.Join(", ", parameters)}) {body}";
        if (SyntaxFactory.ParseMemberDeclaration(signature) is not MethodDeclarationSyntax method || method.ContainsDiagnostics) return null;

        string original = before.ToString();
        string newline = Newline(original);
        var closingLine = before.Lines.GetLineFromPosition(classDeclaration.CloseBraceToken.SpanStart);
        string closingPrefix = original[closingLine.Start..classDeclaration.CloseBraceToken.SpanStart];
        bool closingOwnLine = closingPrefix.All(character => character is ' ' or '\t');
        var declarationLine = before.Lines.GetLineFromPosition(classDeclaration.SpanStart);
        string classIndent = new(original[declarationLine.Start..classDeclaration.SpanStart].TakeWhile(character => character is ' ' or '\t').ToArray());
        string memberIndent = MemberIndent(before, classDeclaration, classIndent);
        string unit = memberIndent.StartsWith(classIndent, StringComparison.Ordinal) && memberIndent.Length > classIndent.Length
            ? memberIndent[classIndent.Length..] : "    ";
        string formatted = method.NormalizeWhitespace(unit, newline).ToFullString();
        formatted = string.Join(newline, formatted.Split(newline).Select(line => memberIndent + line));
        int insertion = closingOwnLine ? closingLine.Start : classDeclaration.CloseBraceToken.SpanStart;
        // Insert immediately before the active close brace, after any preceding
        // directive trivia. Unrelated conditional members remain byte-for-byte intact.
        string prefix = insertion > 0 && original[insertion - 1] is not ('\r' or '\n') || classDeclaration.Members.Count > 0 ? newline : "";
        string inserted = prefix + formatted + newline + (closingOwnLine ? "" : classIndent);
        var edit = new TextEdit(insertion, 0, inserted);

        // Rebind the exact insertion and a temporary method-group assignment in
        // the original partial class. No probe or generated code is returned.
        string probeName = "__WpfStudioEventProbe_" + Guid.NewGuid().ToString("N");
        string probe = $"{newline}private void {probeName}() {{ {target.DelegateType.ToDisplayString(TypeFormat)} value = this.{handlerName}; }}{newline}";
        var candidate = source.WithText(before.WithChanges(new TextChange(new TextSpan(insertion, 0), inserted + probe)));
        var candidateRoot = await candidate.GetSyntaxRootAsync(token).ConfigureAwait(false);
        var semantic = await candidate.GetSemanticModelAsync(token).ConfigureAwait(false);
        if (candidateRoot is null || semantic is null) return null;
        var created = candidateRoot.DescendantNodes().OfType<MethodDeclarationSyntax>().SingleOrDefault(node =>
            node.Identifier.ValueText == target.HandlerName && node.SpanStart >= insertion && node.SpanStart < insertion + inserted.Length);
        var check = candidateRoot.DescendantNodes().OfType<MethodDeclarationSyntax>().SingleOrDefault(node => node.Identifier.ValueText == probeName);
        if (created is null || check is null || created.ContainsDiagnostics || check.ContainsDiagnostics ||
            semantic.GetDeclaredSymbol(created, token) is not { MethodKind: MethodKind.Ordinary, IsStatic: false } ||
            semantic.GetDiagnostics(created.Span, token).Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error) ||
            semantic.GetDiagnostics(check.Span, token).Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)) return null;
        return new(sourcePath, original, edit);
    }

    private static bool SupportedType(ITypeSymbol type, Compilation compilation, INamedTypeSymbol within, int depth = 0)
    {
        if (depth > 16 || type.TypeKind is TypeKind.Error or TypeKind.Pointer or TypeKind.FunctionPointer or TypeKind.TypeParameter ||
            type.IsAnonymousType || type.IsRefLikeType) return false;
        if (type.SpecialType == SpecialType.System_Void || type.TypeKind == TypeKind.Dynamic) return true;
        if (type is IArrayTypeSymbol array) return SupportedType(array.ElementType, compilation, within, depth + 1);
        return type is INamedTypeSymbol named && compilation.IsSymbolAccessibleWithin(named, within) &&
            named.TypeArguments.All(argument => SupportedType(argument, compilation, within, depth + 1));
    }

    private static string? EscapeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name) || name.Length > 256 || name[0] == '@') return null;
        string escaped = SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None ? "@" + name : name;
        var token = SyntaxFactory.ParseToken(escaped);
        return token.IsKind(SyntaxKind.IdentifierToken) && !token.ContainsDiagnostics && token.Text == escaped && token.ValueText == name ? escaped : null;
    }

    private static bool GeneratedPath(string path) => path.Replace('\\', '/').Contains("/obj/", StringComparison.OrdinalIgnoreCase) ||
        path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) || path.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase) ||
        path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) || path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);

    private static string Newline(string text)
    {
        int first = text.IndexOfAny(['\r', '\n']);
        return first < 0 ? Environment.NewLine : text[first] == '\r' ? first + 1 < text.Length && text[first + 1] == '\n' ? "\r\n" : "\r" : "\n";
    }

    private static string MemberIndent(SourceText text, ClassDeclarationSyntax declaration, string classIndent)
    {
        foreach (var member in declaration.Members)
        {
            var line = text.Lines.GetLineFromPosition(member.SpanStart);
            string indentation = text.ToString(TextSpan.FromBounds(line.Start, member.SpanStart));
            if (indentation.Length > classIndent.Length && indentation.All(character => character is ' ' or '\t')) return indentation;
        }
        return classIndent + (classIndent.Contains('\t') ? "\t" : "    ");
    }
}
