using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using WpfStudio.Contracts;
using WpfStudio.Workspace.Xaml;

namespace WpfStudio.Workspace.Tests;

public sealed class XamlEventGenerationTests
{
    private static readonly IReadOnlyList<MetadataReference> References = ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
        .Split(Path.PathSeparator).Select(path => MetadataReference.CreateFromFile(path)).ToArray();
    private const string Xaml = "<local:View xmlns:local='clr-namespace:Demo' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' x:Class='Demo.View' Activated='OnActivated'/>";

    [Theory]
    [InlineData("\r\n", "    ")]
    [InlineData("\n", "\t")]
    public async Task GeneratesActualDelegateSignatureWithoutReformattingExistingMembers(string newline, string indent)
    {
        string source = string.Join(newline, ["namespace Demo;", "public partial class View", "{", indent + "// Keep this exact spacing.",
            indent + "public event global::System.EventHandler<Args>? Activated;", indent + "public int Existing()=> 7;", "}",
            "public class Args : global::System.EventArgs { }"]);
        using var fixture = await Fixture.CreateAsync(source);
        var proposal = Assert.IsType<XamlEventHandlerProposal>(await fixture.GenerateAsync());
        string changed = Apply(source, proposal.Edit);
        Assert.Equal(source, proposal.OriginalText);
        Assert.Equal(source, changed.Remove(proposal.Edit.Start, proposal.Edit.NewText.Length));
        Assert.Contains(indent + "private void OnActivated(object? sender, global::Demo.Args e)", changed);
        Assert.Contains(indent + "public int Existing()=> 7;", changed);
        Assert.DoesNotContain(newline == "\n" ? "\r" : "\n", newline == "\n" ? proposal.Edit.NewText : proposal.Edit.NewText.Replace("\r\n", "", StringComparison.Ordinal));
        var candidate = fixture.Project.Solution.WithDocumentText(fixture.Document.Id, SourceText.From(changed)).GetProject(fixture.Project.Id)!;
        var compilation = await candidate.GetCompilationAsync();
        Assert.DoesNotContain(compilation!.GetDiagnostics(), diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
        Assert.Empty(new XamlEventService().Analyze("View.xaml", Xaml, 1, compilation));
    }

    [Fact]
    public async Task EscapesKeywordsAndPreservesNonVoidAndReferenceParameterSignature()
    {
        const string source = "namespace Demo; public delegate bool Change(ref int @event, out string result, in double value); public partial class View { public event Change Activated; }";
        using var fixture = await Fixture.CreateAsync(source);
        var proposal = Assert.IsType<XamlEventHandlerProposal>(await fixture.GenerateAsync(Xaml.Replace("OnActivated", "class", StringComparison.Ordinal)));
        string changed = Apply(source, proposal.Edit);
        Assert.Contains("private bool @class(", changed);
        Assert.Contains("ref int @event", changed);
        Assert.Contains("out string result", changed);
        Assert.Contains("in double value", changed);
        Assert.Contains("throw new global::System.NotImplementedException();", changed);
        var candidate = fixture.Project.Solution.WithDocumentText(fixture.Document.Id, SourceText.From(changed)).GetProject(fixture.Project.Id)!;
        Assert.DoesNotContain((await candidate.GetCompilationAsync())!.GetDiagnostics(), diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    [Theory]
    [InlineData("public void OnActivated() { }")]
    [InlineData("private int OnActivated;")]
    [InlineData("public string OnActivated => \"conflict\";")]
    [InlineData("public static void OnActivated(object sender, global::System.EventArgs e) { }")]
    public async Task AnyExistingMemberPreventsDuplicateGeneration(string member)
    {
        using var fixture = await Fixture.CreateAsync("namespace Demo; public partial class View { public event global::System.EventHandler Activated; " + member + " }");
        Assert.Null(await fixture.GenerateAsync());
    }

    [Theory]
    [InlineData("View.g.cs", "")]
    [InlineData("View.Designer.cs", "")]
    [InlineData("View.cs", "// <auto-generated />\n")]
    public async Task GeneratedDeclarationsNeverReceiveAnEdit(string name, string header)
    {
        using var fixture = await Fixture.CreateAsync(header + "namespace Demo; public partial class View { public event global::System.EventHandler Activated; }", name);
        Assert.Null(await fixture.GenerateAsync());
    }

    [Fact]
    public async Task MultipleAuthoredPartialFragmentsAreAmbiguousButConditionalMembersArePreserved()
    {
        const string source = "namespace Demo;\npublic partial class View\n{\n#if DEBUG\n    public int DebugOnly;\n#endif\n    public event global::System.EventHandler Activated;\n}\n";
        using var fixture = await Fixture.CreateAsync(source);
        var proposal = Assert.IsType<XamlEventHandlerProposal>(await fixture.GenerateAsync());
        Assert.Contains("#if DEBUG\n    public int DebugOnly;\n#endif", Apply(source, proposal.Edit));
        string second = Path.Combine(fixture.Directory, "Other.cs");
        await File.WriteAllTextAsync(second, "namespace Demo; public partial class View { }");
        fixture.AddDocument(second, "namespace Demo; public partial class View { }");
        Assert.Null(await fixture.GenerateAsync());
    }

    [Fact]
    public async Task UnsavedCSharpIsUsedAndCancellationDoesNotYieldAnEdit()
    {
        const string source = "namespace Demo; public partial class View { public event global::System.EventHandler Activated; }";
        using var fixture = await Fixture.CreateAsync(source);
        string unsaved = source.Replace(" }", " public int Unsaved => 42; }", StringComparison.Ordinal);
        fixture.Update(unsaved);
        var proposal = Assert.IsType<XamlEventHandlerProposal>(await fixture.GenerateAsync());
        Assert.Equal(unsaved, proposal.OriginalText);
        Assert.Equal(source, await File.ReadAllTextAsync(proposal.Path));
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => fixture.GenerateAsync(token: cancellation.Token));
    }

    [Fact]
    public async Task ConventionalCodeBehindDisambiguatesSeparateLogicPartials()
    {
        const string source = "namespace Demo; public partial class View { public event global::System.EventHandler Activated; }";
        using var fixture = await Fixture.CreateAsync(source, "View.xaml.cs");
        string other = Path.Combine(fixture.Directory, "View.Logic.cs");
        await File.WriteAllTextAsync(other, "namespace Demo; public partial class View { public int Existing => 42; }");
        fixture.AddDocument(other, await File.ReadAllTextAsync(other));
        var proposal = Assert.IsType<XamlEventHandlerProposal>(await fixture.GenerateAsync());
        Assert.Equal(fixture.Document.FilePath, proposal.Path);
        Assert.Equal("namespace Demo; public partial class View { public int Existing => 42; }", await File.ReadAllTextAsync(other));
    }

    [Theory]
    [InlineData("net8.0-windows")]
    [InlineData("net9.0-windows")]
    [InlineData("net10.0-windows")]
    public async Task RealWorkerReturnsGuardedUnsavedCodeBehindEditThatBuildsAsCompiledWpf(string framework)
    {
        string directory = Path.Combine(Path.GetTempPath(), "WpfStudio-XamlEventBuild-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        string project = Path.Combine(directory, "Fixture.csproj"), xamlPath = Path.Combine(directory, "View.xaml"), codePath = xamlPath + ".cs";
        const string markup = "<Window xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' x:Class='Demo.View'><Window.Resources><Style x:Key='Clicks' TargetType='Button'><EventSetter Event='Click' Handler='OnSave'/></Style></Window.Resources><Grid Button.Click='OnSave' Mouse.MouseEnter='OnSave'><Button x:Name='SaveButton' Style='{StaticResource Clicks}' Click='OnSave'/></Grid></Window>";
        const string source = "using System.Windows;\r\nnamespace Demo;\r\npublic partial class View : Window\r\n{\r\n    public View() { InitializeComponent(); }\r\n}\r\n";
        await File.WriteAllTextAsync(project, $"<Project Sdk='Microsoft.NET.Sdk'><PropertyGroup><TargetFramework>{framework}</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable></PropertyGroup></Project>");
        await File.WriteAllTextAsync(xamlPath, markup);
        await File.WriteAllTextAsync(codePath, source);
        try
        {
            Assert.Equal(0, (await new BuildService().RunAsync(new(project, BuildOperation.Restore, "Release"))).ExitCode);
            await using var client = new WorkspaceClient();
            await client.LoadAsync(new(project, "Release"));
            string unsaved = source.Replace("    public View()", "    public int Unsaved => 42;\r\n    public View()", StringComparison.Ordinal);
            Assert.True((await client.UpdateDocumentAsync(new(codePath, unsaved, 9, Analyze: false))).Accepted);
            var action = Assert.Single(await client.GetXamlCodeActionsAsync(new(xamlPath, markup, markup.LastIndexOf("OnSave", StringComparison.Ordinal), 4)));
            Assert.Empty(action.Edit.Edits);
            Assert.Equal(4, action.Edit.Version);
            Assert.Equal(Hash(markup), action.Edit.ExpectedTextHash);
            var codeEdit = Assert.Single(action.AdditionalEdits!);
            Assert.Equal(codePath, codeEdit.Path);
            Assert.Equal(9, codeEdit.Version);
            Assert.Equal(Hash(unsaved), codeEdit.ExpectedTextHash);
            string changed = codeEdit.Edits.Aggregate(unsaved, Apply);
            Assert.Contains("global::System.Windows.RoutedEventArgs", changed);
            Assert.Contains("Unsaved => 42", changed);
            Assert.Equal(source, await File.ReadAllTextAsync(codePath));
            Assert.True((await client.UpdateDocumentAsync(new(codePath, changed, 10, Analyze: false))).Accepted);
            Assert.DoesNotContain((await client.AnalyzeXamlAsync(new(xamlPath, markup, 4))).Diagnostics, diagnostic => diagnostic.Id.StartsWith("XAMLEVENT", StringComparison.Ordinal));
            Assert.Empty(await client.GetXamlCodeActionsAsync(new(xamlPath, markup, markup.LastIndexOf("OnSave", StringComparison.Ordinal), 4)));
            // Only the test applies/saves the proposal, to exercise the real WPF
            // markup compiler's generated delegate wiring in an isolated fixture.
            await File.WriteAllTextAsync(codePath, changed);
            var build = await new BuildService().RunAsync(new(project, BuildOperation.Build, "Release"));
            Assert.True(build.ExitCode == 0, string.Join("\n", build.Diagnostics.Select(diagnostic => diagnostic.Message)));

            // These new names exist only in the XAML request, not in the worker's
            // generated partial class or on disk. Both forms will become fields
            // when this buffer is compiled; the aliased directive also uses an entity.
            string empty = markup.Replace("Style='{StaticResource Clicks}' Click='OnSave'", "Style='{StaticResource Clicks}' Click=''", StringComparison.Ordinal)
                .Replace("</Grid>", "<TextBlock xmlns:n='http://schemas.microsoft.com/winfx/2006/xaml' n:Name='SaveButton_Cl&#105;ck'/><TextBlock Name='SaveButton_Click1'/></Grid>", StringComparison.Ordinal);
            Assert.Equal(markup, await File.ReadAllTextAsync(xamlPath));
            Assert.DoesNotContain("SaveButton_Click", changed);
            foreach (string reserved in new[] { "SaveButton_Click", "SaveButton_Click1" })
            {
                string collision = empty.Replace("Click=''", "Click='" + reserved + "'", StringComparison.Ordinal);
                Assert.Empty(await client.GetXamlCodeActionsAsync(new(xamlPath, collision,
                    collision.LastIndexOf("Click='" + reserved + "'", StringComparison.Ordinal) + 7, 5)));
            }
            string designNames = empty.Replace("<Window ", "<Window xmlns:d='http://schemas.microsoft.com/expression/blend/2008' xmlns:mc='http://schemas.openxmlformats.org/markup-compatibility/2006' mc:Ignorable='d' ", StringComparison.Ordinal)
                .Replace("</Grid>", "<TextBlock d:Name='SaveButton_Click2'/><d:Ignored x:Name='SaveButton_Click2'><TextBlock Name='SaveButton_Click2'/></d:Ignored></Grid>", StringComparison.Ordinal);
            var designAction = Assert.Single(await client.GetXamlCodeActionsAsync(new(xamlPath, designNames, designNames.LastIndexOf("Click='", StringComparison.Ordinal) + 7, 5)));
            Assert.Equal("SaveButton_Click2", Assert.Single(designAction.Edit.Edits).NewText);
            var emptyAction = Assert.Single(await client.GetXamlCodeActionsAsync(new(xamlPath, empty, empty.LastIndexOf("Click='", StringComparison.Ordinal) + 7, 5)));
            Assert.Equal("SaveButton_Click2", Assert.Single(emptyAction.Edit.Edits).NewText);
            Assert.Equal(Hash(empty), emptyAction.Edit.ExpectedTextHash);
            var emptyCodeEdit = Assert.Single(emptyAction.AdditionalEdits!);
            string withEmptyHandler = emptyCodeEdit.Edits.Aggregate(changed, Apply);
            Assert.True((await client.UpdateDocumentAsync(new(codePath, withEmptyHandler, 11, Analyze: false))).Accepted);
            var nextEmpty = Assert.Single(await client.GetXamlCodeActionsAsync(new(xamlPath, empty, empty.LastIndexOf("Click='", StringComparison.Ordinal) + 7, 5)));
            Assert.Equal("SaveButton_Click3", Assert.Single(nextEmpty.Edit.Edits).NewText);
            await File.WriteAllTextAsync(xamlPath, emptyAction.Edit.Edits.Aggregate(empty, Apply));
            await File.WriteAllTextAsync(codePath, withEmptyHandler);
            var emptyBuild = await new BuildService().RunAsync(new(project, BuildOperation.Build, "Release"));
            Assert.True(emptyBuild.ExitCode == 0, string.Join("\n", emptyBuild.Diagnostics.Select(diagnostic => diagnostic.Message)));
        }
        finally { Directory.Delete(directory, recursive: true); }
    }

    private static string Apply(string text, TextEdit edit) => text.Remove(edit.Start, edit.Length).Insert(edit.Start, edit.NewText);
    private static string Hash(string text) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(text)));

    private sealed class Fixture : IDisposable
    {
        private readonly AdhocWorkspace _workspace = new();
        public string Directory { get; } = Path.Combine(Path.GetTempPath(), "WpfStudio-XamlEvent-" + Guid.NewGuid().ToString("N"));
        public Document Document { get; private set; } = null!;
        public Project Project => _workspace.CurrentSolution.GetProject(Document.Project.Id)!;

        public static async Task<Fixture> CreateAsync(string source, string name = "View.cs")
        {
            var fixture = new Fixture();
            System.IO.Directory.CreateDirectory(fixture.Directory);
            var project = fixture._workspace.AddProject(ProjectInfo.Create(ProjectId.CreateNewId(), VersionStamp.Create(), "Demo", "Demo", LanguageNames.CSharp,
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview),
                compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable), metadataReferences: References));
            string path = Path.Combine(fixture.Directory, name);
            await File.WriteAllTextAsync(path, source);
            fixture.Document = fixture._workspace.AddDocument(DocumentInfo.Create(DocumentId.CreateNewId(project.Id), name,
                filePath: path, loader: TextLoader.From(TextAndVersion.Create(SourceText.From(source), VersionStamp.Create()))));
            return fixture;
        }
        public void AddDocument(string path, string text) => _workspace.AddDocument(DocumentInfo.Create(DocumentId.CreateNewId(Project.Id), Path.GetFileName(path),
            filePath: path, loader: TextLoader.From(TextAndVersion.Create(SourceText.From(text), VersionStamp.Create()))));
        public void Update(string text)
        {
            Assert.True(_workspace.TryApplyChanges(Project.Solution.WithDocumentText(Document.Id, SourceText.From(text))));
            Document = _workspace.CurrentSolution.GetDocument(Document.Id)!;
        }
        public async Task<XamlEventHandlerProposal?> GenerateAsync(string xaml = Xaml, CancellationToken token = default)
        {
            var compilation = (await Project.GetCompilationAsync(token))!;
            int caret = xaml.IndexOf("Activated='", StringComparison.Ordinal) + "Activated='".Length;
            var target = new XamlEventService().GetTarget(xaml, caret, compilation, token);
            return target is null ? null : await XamlEventHandlerGenerator.CreateAsync(Project, compilation, target, token, Path.Combine(Directory, "View.xaml"));
        }
        public void Dispose() { _workspace.Dispose(); System.IO.Directory.Delete(Directory, recursive: true); }
    }
}
